apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-message-handler
  labels:
    app: product-message-handler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: product-message-handler
  template:
    metadata:
      name: product-message-handler
      labels:
        app: product-message-handler
    spec:
      initContainers:
        - name: product-migrator
          image: ordering-app-productservice:latest
          imagePullPolicy: Never
          command:
            - /app/productservice
          args:
            - migrate
          env:
            - name: PRODUCT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PRODUCT_DATABASE_NAME
              value: productservice_db
            - name: PRODUCT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_USER
            - name: PRODUCT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_PASSWORD
      containers:
        - name: product-message-handler
          image: ordering-app-productservice:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/productservice
          args:
            - message-handler
          env:
            - name: PRODUCT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PRODUCT_DATABASE_NAME
              value: productservice_db
            - name: PRODUCT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_USER
            - name: PRODUCT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_PASSWORD
            - name: PRODUCT_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:5672
            - name: PRODUCT_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: PRODUCT_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always