apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  labels:
    app: product-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      name: product-api
      labels:
        app: product-api
    spec:
      initContainers:
        - name: product-migrator
          image: ordering-app-productservice:latest
          imagePullPolicy: Never
          command:
            - /app/productservice
          args:
            - migrate
          env:
            - name: PRODUCT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PRODUCT_DATABASE_NAME
              value: productservice_db
            - name: PRODUCT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_USER
            - name: PRODUCT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_PASSWORD
      containers:
        - name: product-api
          image: ordering-app-productservice:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/productservice
          args:
            - service
          env:
            - name: PRODUCT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PRODUCT_DATABASE_NAME
              value: productservice_db
            - name: PRODUCT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_USER
            - name: PRODUCT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-database-access
                  key: PRODUCT_DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always