apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      name: user-api
      labels:
        app: user-api
    spec:
      initContainers:
        - name: user-migrator
          image: user:latest
          imagePullPolicy: Never
          command:
            - migrate
          env:
            - name: USER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: USER_DATABASE_NAME
              value: userservice_db
            - name: USER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_USER
            - name: USER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_PASSWORD
      containers:
        - name: user-api
          image: user:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - service
          env:
            - name: USER_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: USER_DATABASE_NAME
              value: userservice_db
            - name: USER_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_USER
            - name: USER_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-database-access
                  key: USER_DATABASE_PASSWORD
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always
      