apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-message-handler
  labels:
    app: notification-message-handler
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: notification-message-handler
  template:
    metadata:
      name: notification-message-handler
      labels:
        app: notification-message-handler
    spec:
      initContainers:
        - name: notification-migrator
          image: ordering-app-notificationservice:latest
          imagePullPolicy: Never
          command:
            - /app/notificationservice
          args:
            - migrate
          env:
            - name: NOTIFICATION_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: NOTIFICATION_DATABASE_NAME
              value: notificationservice_db
            - name: NOTIFICATION_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_USER
            - name: NOTIFICATION_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_PASSWORD
      containers:
        - name: notification-message-handler
          image: ordering-app-notificationservice:latest
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
          readinessProbe:
            httpGet:
              port: http
              path: /healthz
          imagePullPolicy: Never
          command:
            - /app/notificationservice
          args:
            - message-handler
          env:
            - name: NOTIFICATION_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: NOTIFICATION_DATABASE_NAME
              value: notificationservice_db
            - name: NOTIFICATION_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_USER
            - name: NOTIFICATION_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-database-access
                  key: NOTIFICATION_DATABASE_PASSWORD
            - name: NOTIFICATION_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:15672
            - name: NOTIFICATION_AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: NOTIFICATION_AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
          ports:
            - containerPort: 8081
              protocol: TCP
              name: grpc
            - containerPort: 8082
              protocol: TCP
              name: http
      restartPolicy: Always